name: Playa Tarot CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - uses: actions/checkout@v4

    # Setup Node.js
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'npm'

    # Install dependencies
    - name: Install dependencies
      run: npm ci


    # Build the project
    - name: Build
      run: npm run build

    # Upload build artifacts
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: playa-tarot-build
        path: build

